import { useState, useEffect } from 'react';
import toast from 'react-hot-toast';
import api from '../api/axios';
import { CheckCircle, XCircle, FileText, FileDown } from 'lucide-react';

export default function ManagerQuotationView() {
  const [quotations, setQuotations] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchQuotations = async () => {
    try {
      setLoading(true);
      const res = await api.get('/quotations');
      // Filter quotations that need manager approval (Level 2)
      const data = res.data.data || [];
      const pendingForManager = data.filter(q => 
        q.status === 'pending_approval' && 
        q.approvals.some(a => a.level === 2 && a.status === 'pending')
      );
      setQuotations(pendingForManager);
    } catch (err) {
      console.error(err);
      toast.error("Failed to fetch quotations for approval");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchQuotations();
  }, []);

  const handleApprovalAction = async (id, level, status) => {
    try {
      const res = await api.put(`/quotations/${id}/approve`, { 
        level, 
        remarks: `Actioned as ${status}`,
        status 
      });
      toast.success(`Quotation ${status} successfully`);
      // Remove the quotation from the list after action
      setQuotations(prev => prev.filter(q => q._id !== id));
    } catch (err) {
      console.error(err);
      toast.error("Action failed");
    }
  };

  const handleDownloadPDF = async (id) => {
    try {
      toast.loading("Generating PDF...");
      const response = await api.post(`/quotations/${id}/generate-pdf`, {}, {
        responseType: 'blob',
      });
      
      // Check if response is actually a blob
      if (!(response.data instanceof Blob)) {
        throw new Error("Invalid response format");
      }
      
      // Create blob and download
      const blob = new Blob([response.data], { type: 'application/pdf' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `quotation-${id}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
      
      toast.dismiss();
      toast.success("PDF downloaded successfully!");
    } catch (error) {
      console.error("PDF Download Error:", error);
      toast.dismiss();
      
      // Try to get error message from response
      let errorMessage = "Failed to download PDF";
      if (error.response?.data) {
        const reader = new FileReader();
        reader.onload = () => {
          try {
            const errorData = JSON.parse(reader.result);
            errorMessage = errorData.message || errorMessage;
          } catch {
            errorMessage = "Server error occurred";
          }
          toast.error(errorMessage);
        };
        reader.readAsText(error.response.data);
      } else {
        toast.error(error.message || errorMessage);
      }
    }
  };

  if (loading) {
    return (
      <div className="p-8 bg-[#121212] min-h-screen flex items-center justify-center">
        <p className="text-gray-400 text-lg font-medium">Loading quotations...</p>
      </div>
    );
  }

  return (
    <div className="p-8 bg-[#121212] min-h-screen text-white">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-orange-400">Manager Approval Queue</h1>
        <p className="text-gray-400 mt-1">Review and approve quotations requiring your authorization</p>
      </div>
      
      <div className="space-y-4">
        {quotations.length === 0 ? (
          <div className="bg-[#1f1f1f] border border-orange-500/20 rounded-xl p-12 text-center">
            <FileText size={64} className="mx-auto text-gray-600 mb-4" />
            <p className="text-gray-400 text-lg">No quotations currently awaiting your approval.</p>
            <p className="text-sm mt-2 text-gray-500">Quotations between ₹50,000 and ₹2,00,000 require your approval.</p>
          </div>
        ) : (
          quotations.map(q => (
            <div key={q._id} className="bg-[#1f1f1f] border-l-4 border-orange-500 p-6 rounded-xl shadow-md hover:shadow-lg transition-shadow">
              <div className="flex justify-between items-start">
                <div className="flex-1">
                  <h2 className="text-xl font-bold text-white">{q.clientName}</h2>
                  <p className="text-gray-400 text-sm mt-1">Generated by: <span className="text-gray-300 font-medium">{q.createdBy?.name || 'Sales Rep'}</span></p>
                  <div className="mt-4 grid grid-cols-2 gap-4 text-sm">
                    <div className="bg-[#121212] border border-blue-500/20 px-4 py-2 rounded-lg inline-block">
                      <p className="text-xs text-gray-400 font-medium">Subtotal</p>
                      <p className="text-lg font-bold text-blue-400">₹{q.subtotal?.toLocaleString()}</p>
                    </div>
                    <div className="bg-[#121212] border border-green-500/20 px-4 py-2 rounded-lg inline-block">
                      <p className="text-xs text-gray-400 font-medium">Grand Total</p>
                      <p className="text-lg font-bold text-green-400">₹{q.grandTotal?.toLocaleString()}</p>
                    </div>
                  </div>
                  <div className="mt-3 flex gap-2">
                    <span className="text-xs px-3 py-1 rounded-full bg-yellow-500/20 text-yellow-400 border border-yellow-500/30 font-semibold">
                      Pending Approval
                    </span>
                    <span className="text-xs px-3 py-1 rounded-full bg-orange-500/20 text-orange-400 border border-orange-500/30 font-semibold">
                      Level 2 Required
                    </span>
                  </div>
                </div>
                
                <div className="flex flex-col gap-2">
                  {q.approvals.filter(a => a.level === 2 && a.status === 'pending').map(app => (
                    <div key={app.level} className="flex gap-2">
                      <button 
                        onClick={() => handleApprovalAction(q._id, app.level, 'approved')}
                        className="bg-green-600 text-white px-5 py-2.5 rounded-lg flex items-center gap-2 hover:bg-green-700 transition shadow-md font-medium"
                      >
                        <CheckCircle size={18}/> Approve
                      </button>
                      <button 
                        onClick={() => handleApprovalAction(q._id, app.level, 'rejected')}
                        className="bg-red-600 text-white px-5 py-2.5 rounded-lg flex items-center gap-2 hover:bg-red-700 transition shadow-md font-medium"
                      >
                        <XCircle size={18}/> Reject
                      </button>
                      <button 
                        onClick={() => handleDownloadPDF(q._id)}
                        className="bg-blue-600 text-white px-5 py-2.5 rounded-lg flex items-center gap-2 hover:bg-blue-700 transition shadow-md font-medium"
                      >
                        <FileDown size={18}/> PDF
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}